name: poster
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_ui_auth: ^1.2.0
  firebase_storage: ^11.1.0
  firebase_ui_firestore: ^1.5.11

  font_awesome_flutter: ^10.4.0
  loading_animation_widget: ^1.2.0+4
  image_cropper: ^4.0.1
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1

  url_launcher: ^6.1.11
  url_strategy: ^0.2.0
  get: ^4.6.5
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  json_annotation: ^4.8.0
  dio: ^5.3.2
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  http: ^0.13.5
  uuid: 3.0.7
  photo_view: 0.14.0
  js: ^0.6.5
  extended_nested_scroll_view: ^6.1.2
  auto_size_text: ^3.0.0
  flutter_stripe: ^9.3.0
  window_location_href: ^1.0.1+2
  go_router: ^10.1.2
  dart_mailgun: ^1.0.3
  webview_flutter_web: ^0.2.2
  pointer_interceptor: ^0.9.3+4
  image: ^4.1.3
  fluttertoast: ^8.2.4
  preload_page_view: ^0.2.0
  firebase_analytics: ^10.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/html/

  fonts:
    - family: Goldman
      fonts:
        - asset: assets/fonts/Goldman/Goldman-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/nunito.ttf

    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri/calibri.ttf